resources:
- repo: self

pool:
  name: Hosted Ubuntu 1604
steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'ACR Connection'
    azureContainerRegistry: '{"loginServer":"openhacknwm4acr.azurecr.io", "id" : "/subscriptions/d25a0594-50be-4cee-8509-1125541f419d/resourceGroups/openhacknwm4rg/providers/Microsoft.ContainerRegistry/registries/openhacknwm4acr"}'
    dockerFile: apis/userprofile/Dockerfile
    imageName: 'openhacknwm4acr.azurecr.io/devopsoh/api-userprofile:$(Build.BuildId)'

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'OTA-PRD-217 (d25a0594-50be-4cee-8509-1125541f419d)'
    azureContainerRegistry: '{"loginServer":"openhacknwm4acr.azurecr.io", "id" : "/subscriptions/d25a0594-50be-4cee-8509-1125541f419d/resourceGroups/openhacknwm4rg/providers/Microsoft.ContainerRegistry/registries/openhacknwm4acr"}'
    action: 'Push an image'
    imageName: 'openhacknwm4acr.azurecr.io/devopsoh/api-userprofile:$(Build.BuildId)'

- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: apis/userprofile

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - apis/userprofile


