resources:
- repo: self

pool:
  name: Hosted Ubuntu 1604
steps:
- task: Go@0
  inputs:
    command: 'test'
    arguments: '/apis/trips/tests'
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'ACR Connection'
    azureContainerRegistry: '{"loginServer":"openhacknwm4acr.azurecr.io", "id" : "/subscriptions/d25a0594-50be-4cee-8509-1125541f419d/resourceGroups/openhacknwm4rg/providers/Microsoft.ContainerRegistry/registries/openhacknwm4acr"}'
    dockerFile: apis/trips/Dockerfile
    imageName: 'openhacknwm4acr.azurecr.io/devopsoh/api-trips:$(Build.BuildId)'
- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'OTA-PRD-217 (d25a0594-50be-4cee-8509-1125541f419d)'
    azureContainerRegistry: '{"loginServer":"openhacknwm4acr.azurecr.io", "id" : "/subscriptions/d25a0594-50be-4cee-8509-1125541f419d/resourceGroups/openhacknwm4rg/providers/Microsoft.ContainerRegistry/registries/openhacknwm4acr"}'
    action: 'Push an image'
    imageName: 'openhacknwm4acr.azurecr.io/devopsoh/api-trips:$(Build.BuildId)'
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - apis/trips